### ISSUE TITLE
Prepare ScanNet Pre-training Data

### ISSUE THREAD

**Issue by ydzat** [Sekunde/Pri3D#7]
In the Prepare ScanNet Pre-training Data section, TARGET and SCANNET_DIR need to be modified, but what data should be stored in the folders pointed to by these two parameters in what structure?

I downloaded ScanNet's scannet_frames_25k data and its structure is:

```
 <scannet_frames_25k>
  |---- <scene0000_00>                  
        |---- <color>
                |---- 000000.jpg
                |---- 000100.jpg
                |---- 000200.jpg
                |---- ... # RGB images
        |---- <depth>
                |---- 000000.png
                |---- 000100.png
                |---- 000200.png
                |---- ... # depth images
        |---- <instance>
                |---- 000000.png
                |---- 000100.png
                |---- 000200.png
                |---- ... # instance images
        |---- <label>
                |---- 000000.png
                |---- 000100.png
                |---- 000200.png
                |---- ... # label images
        |---- <pose>
                |---- 000000.txt
                |---- 000100.txt
                |---- 000200.txt
                |---- ... # camera poses
        |---- intrinsics_color.txt
        |---- intrinsics_depth.txt
  |---- <scene0000_01>   
        |---- ... # same structure as before 
  |---- ... # like <scene*>  
```

Is the above data to be put into the TARGET or SCANNET_DIR mentioned before? Or do I have to download the specified ScanNet scene separately, e.g. scene0000_00, with the following structure:

```
<scanId>
|-- <scanId>.sens
    RGB-D sensor stream containing color frames, depth frames, camera poses and other data
|-- <scanId>_vh_clean.ply
    High quality reconstructed mesh
|-- <scanId>_vh_clean_2.ply
    Cleaned and decimated mesh for semantic annotations
|-- <scanId>_vh_clean_2.0.010000.segs.json
    Over-segmentation of annotation mesh
|-- <scanId>.aggregation.json, <scanId>_vh_clean.aggregation.json
    Aggregated instance-level semantic annotations on lo-res, hi-res meshes, respectively
|-- <scanId>_vh_clean_2.0.010000.segs.json, <scanId>_vh_clean.segs.json
    Over-segmentation of lo-res, hi-res meshes, respectively (referenced by aggregated semantic annotations)
|-- <scanId>_vh_clean_2.labels.ply
    Visualization of aggregated semantic segmentation; colored by nyu40 labels (see img/legend; ply property 'label' denotes the nyu40 label id)
|-- <scanId>_2d-label.zip
    Raw 2d projections of aggregated annotation labels as 16-bit pngs with ScanNet label ids
|-- <scanId>_2d-instance.zip
    Raw 2d projections of aggregated annotation instances as 8-bit pngs
|-- <scanId>_2d-label-filt.zip
    Filtered 2d projections of aggregated annotation labels as 16-bit pngs with ScanNet label ids
|-- <scanId>_2d-instance-filt.zip
    Filtered 2d projections of aggregated annotation instances as 8-bit pngs
```

So, what I am asking is: what files should I put into TARGET and SCANNET_DIR?

**Comment by ydzat** [comment]
+ Error when running `./preprocess.sh`

I tried to solve the previous problem, and set both TARGET and SCANNET_DIR to the path of `<data>`, it looks like:

```
<data>
|--  <scans>
      |--  <scanId>
            |-- <scanId>.sens
            |-- ...
```

and then, I run `./preprocess.sh`, after running for a while, an error is reported, the output is:

```
# Only the last part has been intercepted
...
Saving npz file...
================================================== : /mnt/g/AI/ScanNet_00/data/scene0000_00/pose/5550.txt
Camera pose:
[[-9.995960e-01  2.423000e-03 -2.832700e-02  2.869053e+00]
 [ 2.697400e-02  3.956430e-01 -9.180080e-01  3.192867e+00]
 [ 8.983000e-03 -9.184010e-01 -3.955480e-01  1.403724e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
(278881, 4)
Saving npz file...
================================================== : /mnt/g/AI/ScanNet_00/data/scene0000_00/pose/5575.txt
Camera pose:
[[-0.984802 -0.063071  0.161822  2.769851]
 [-0.172787  0.261493 -0.949614  3.078715]
 [ 0.017578 -0.963142 -0.268417  1.481366]
 [ 0.        0.        0.        1.      ]]
(277264, 4)
Saving npz file...
Compute partial scan overlapping
Namespace(input_path='/mnt/g/AI/ScanNet_00/data/scene0000_00/pcd', voxel_size=0.05)
load point clouds and downsampling...
Traceback (most recent call last):
  File "compute_full_overlapping.py", line 58, in <module>
    _points = [
  File "compute_full_overlapping.py", line 59, in <listcomp>
    (pcd_name, make_open3d_point_cloud(np.load(pcd_name)['pcd'], voxel_size=opt.voxel_size))
  File "compute_full_overlapping.py", line 19, in make_open3d_point_cloud
    pcd.points = o3d.utility.Vector3dVector(xyz)
RuntimeError

real    11m27.874s
user    11m18.826s
sys     2m23.855s
```

How can I fix it?

**Comment by Sekunde** [comment]
do you have anything generated under /mnt/g/AI/ScanNet_00/data/scene0000_00/pcd ?

Runtime Error indicates nothing, can you print **xyz** in line 19 of compute_full_overlapping.py to see what is **xyz** like?

**Comment by ydzat** [comment]
> do you have anything generated under /mnt/g/AI/ScanNet_00/data/scene0000_00/pcd ?
> 
> Runtime Error indicates nothing, can you print **xyz** in line 19 of compute_full_overlapping.py to see what is **xyz** like?

under ./pcd: a lot of `.npz` files are generated.

xyz is:
```
[[1.82709587e+00 1.02583306e+00 1.29226941e+00 ... 2.15000000e+02
  2.03000000e+02 0.00000000e+00]
 [1.82385043e+00 1.02683598e+00 1.29227079e+00 ... 2.12000000e+02
  1.99000000e+02 0.00000000e+00]
 [1.82060499e+00 1.02783890e+00 1.29227218e+00 ... 2.14000000e+02
  2.01000000e+02 0.00000000e+00]
 ...
 [1.48828178e+00 2.10970281e+00 1.48669412e-01 ... 4.40000000e+01
  3.00000000e+01 0.00000000e+00]
 [1.48568146e+00 2.11050637e+00 1.48670523e-01 ... 4.70000000e+01
  3.50000000e+01 0.00000000e+00]
 [1.47860500e+00 2.10798822e+00 1.44015235e-01 ... 3.70000000e+01
  3.00000000e+01 0.00000000e+00]]
```

**Comment by Sekunde** [comment]
that is expected, what is xyz.shape ?

**Comment by ydzat** [comment]
> 

`print(xyz.shape)`
(276497, 7)

**Comment by Sekunde** [comment]
okay, what if you do 
`pcd.points = o3d.utility.Vector3dVector(xyz[:,:3])`

does it work?

**Comment by ydzat** [comment]
> okay, what if you do `pcd.points = o3d.utility.Vector3dVector(xyz[:,:3])`
> 
> does it work?

it works! THANKS!
