### ISSUE TITLE
nyu2coco.py

### ISSUE THREAD

**Issue by miquel-espinosa** [Sekunde/Pri3D#9]
I am encourtering the following error when converting nyu2coco with the provided script.

Did the authors encounter a similar problem when using the pycococreatortools?

Thanks!

```
Traceback (most recent call last):
  File "/nyu2coco.py", line 152, in <module>
    convert_nyu_to_coco(opt.nyu_path, opt.phase)
  File "/nyu2coco.py", line 124, in convert_nyu_to_coco
    ann_info = pycococreatortools.create_annotation_info(
  File "/site-packages/pycococreatortools/pycococreatortools.py", line 99, in create_annotation_info
    segmentation = binary_mask_to_polygon(binary_mask, tolerance)
  File "/site-packages/pycococreatortools/pycococreatortools.py", line 48, in binary_mask_to_polygon
    contours = np.subtract(contours, 1)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
```

**Comment by miquel-espinosa** [comment]
There is a bug in `pycococreatortools`.
For me, fixed with this https://github.com/waspinator/pycococreator/pull/51

**Comment by Zhangxiatian** [comment]
Thanks for your debugging!
